language: node_js

sudo: false

cache:
  apt: true
  derectories: 
    - node_modules

node_js: stable

install: 
  - npm install -D
  - cd ./test/smoke/template
  - npm install -D

 script:  
  - npm test 
